# Meta Data for SEO

## Homepage
title = "web-scraping.org"
titleSeparator = "-"
titleAddition = "web scraping and APIs for academic research"
description = "Manage the challenges in scraping data for academic research."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["webdata.png"]
ogLocale = "en_US"
domainTLD = "web-scraping.org"
titleHome = "Scraping Web Data for Marketing Insights"

## Twitter Cards
twitterSite = "@hannesdatta"
twitterCreator = "@hannesdatta"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Web Data"
schemaAuthor = "Hannes Datta"
schemaAuthorTwitter = "https://twitter.com/hannesdatta"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/hannesdatta/"
schemaAuthorGitHub = "https://github.com/hannesdatta"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "webdata.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/hannesdatta"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/hannesdatta/webdata-website"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Footer
#footer = "Powered by <a class=\"text-muted\" href=\"https://www.netlify.com/\">Netlify</a>, <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"
footer = "Copyright (c) 2022-2023. <a class=\"text-muted\" href=\"/contact\">Contact</a>. <a class=\"text-muted\" href=\"/privacy-policy\">Privacy Policy</a>."
#footer = "Copyright (c) 2022 Johannes Boegershausen and Hannes Datta"
# Feed
copyRight = "Copyright (c) 2023 by the authors."

# Alert
alert = true
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
#alertText = "Join the webinar on June 23, 2022 - <a class=\"alert-link stretched-link\" target=\"_blank\" href=\"https://www.ama.org/events/webinar/jm-webinar-series-insights-for-managers/\">Sign up now!</a>"
#alertText = "Missed our webinar with tips & tricks for researchers? <a class=\"alert-link stretched-link\" target=\"_blank\" href=\"https://youtu.be/KiyFyLEkqNk\">Watch it now on YouTube!</a>"
alertText = "Database now features 400+ papers - Check out our latest podcast <a class=\"alert-link stretched-link\" target=\"_blank\" href=\"https://open.spotify.com/episode/0nllYyKDcOOaQyjVOAcEae?si=1FFOX44BQ82iHqVtexFW0Q&nd=1\">on Spotify!</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/hannesdatta/webdata-website"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = true
lastMod = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = false
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
